### ISSUE TITLE
默认赋值是怎么实现

### ISSUE THREAD

**Issue by roy2651** [suweya/vue-verification-code-input#1]
你好，如果进来以后就想有默认赋值，根据文档我赋值v-on:values="defaultCode",但是无法实现，这个怎么实现的

**Comment by suweya** [comment]
可以传`values`

**Comment by roy2651** [comment]
> 可以传`values`

我是这样使用的：

```
<template>
  <div id="app">
    <CodeInput :loading="false" class="input" v-on:change="onChange" v-on:complete="onComplete" :values="showCode"/>
  </div>
</template>

<script>
import CodeInput from "./components/CodeInput.vue";

export default {
  name: "app",
  components: {
    CodeInput
  },
  data() {
    return {  
     showCode:null
    }
  },
  methods: {
    onChange(v) {
      console.log("onChange ", v);
    },
    onComplete(v) {
      console.log("onComplete ", v);
    },
  },
  mounted() {
    this.showCode = ['1','1','1','1','1','2']
    console.log(this.showCode)
  }
};
</script>
```
这样写我无效

**Comment by suweya** [comment]
现在不支持在`mounted`设置`values`

**Comment by roy2651** [comment]
> 现在不支持在`mounted`设置`values`

我在created里面也不行，请问在哪里可以设置
我想要进页面的时候加载默认值

**Comment by webrtcn** [comment]
貌似实现不了，需要修改源代码，单独写个设置 values 的方法，然后在外面调用。
```
methods: {
       setDefaultValues(val) {
                 this.values = val;
       }
}
```

建议作者增加个 defaultValues  props

**Comment by alhavizd** [comment]
> > 可以传`values`
> 
> 我是这样使用的：
> 
> ```
> <template>
>   <div id="app">
>     <CodeInput :loading="false" class="input" v-on:change="onChange" v-on:complete="onComplete" :values="showCode"/>
>   </div>
> </template>
> 
> <script>
> import CodeInput from "./components/CodeInput.vue";
> 
> export default {
>   name: "app",
>   components: {
>     CodeInput
>   },
>   data() {
>     return {  
>      showCode:null
>     }
>   },
>   methods: {
>     onChange(v) {
>       console.log("onChange ", v);
>     },
>     onComplete(v) {
>       console.log("onComplete ", v);
>     },
>   },
>   mounted() {
>     this.showCode = ['1','1','1','1','1','2']
>     console.log(this.showCode)
>   }
> };
> </script>
> ```
> 
> 这样写我无效

cannot set default/reset data
